id: hl7.fhir.uv.epi-asean
canonical: http://hl7.org/fhir/uv/epi-asean
name: aseanepi
title: ePI IG for APAC markets
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
publisher:
  name: Gravitate Health Project
  url: https://www.gravitatehealth.eu/

pages:
   index.md:
     title: Home
   usecases.md:
     title: Use Cases
   terminology.md:
    title: Terminology
   epiElements.md:
    title: ePI Elements
   TechStyleGuide.md:
    title: Technical Style Guide
   appendix1.md:
    title: Appendix 1
   appendix2.md:
    title: Appendix 2

menu:
  Home: index.html
  Use Cases: usecases.html
  Terminology: terminology.html
  ePI Elements: epiElements.html
  Technical Style Guide: TechStyleGuide.html
  Appendices: 
    Appendix 1: appendix1.html
    Appendix 2: appendix2.html
  Artifacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true
